"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "fg:#e1e1e1"

[character]
success_symbol = "[❯](bold #e1e1e1)"
error_symbol = "[❯](bold #525252)"
vimcmd_symbol = "[❮](bold #7c7c7c)"

[git_branch]
format = "[$branch]($style)"
style = "fg:#7c7c7c"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](fg:#e1e1e1) ($ahead_behind$stashed)]($style)"
style = "fg:#e1e1e1"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "fg:#7c7c7c"

[cmd_duration]
format = "[$duration](fg:#7c7c7c) "
