require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"lua",
		"vimdoc",
		"vim",
		"regex",
		"terraform",
		"sql",
		"dockerfile",
		"toml",
		"json",
		"java",
		"groovy",
		"go",
		"gitignore",
		"graphql",
		"yaml",
		"make",
		"cmake",
		"markdown",
		"markdown_inline",
		"bash",
		"css",
		"html",
		"rust",
	},
	-- Autoinstall languages that are not installed
	auto_install = true,
	highlight = { enable = true },
})
